#SIMPLE CALCULATOR USING USER INPUT; DEVELOPED BY SOYAM KAPOOR
print("<=========================SIMPLE CALCULATOR WITHOUT USING USER INPUT=========================>")
first_number=float(input("Enter First Number "))
second_number=float(input("Enter Second Number "))
print("Addition              =>",first_number,"+",second_number,"=",first_number+second_number)
print("Subtraction           =>",first_number,"-",second_number,"=",first_number-second_number)
print("Multiplication        =>",first_number,"*",second_number,"=",first_number*second_number)
print("Division              =>",first_number,"/",second_number,"=",first_number/second_number)
print("Modulus               =>",first_number,"%",second_number,"=",first_number%second_number)
print("Floor Division 5      =>",first_number,"//",second_number,"=",first_number//second_number)
print("Exponential           =>",first_number,"**",second_number,"=",first_number**second_number)